name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: ✨ Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: 🚚 Restore
        run: dotnet restore src
      - name: 🛠️ Build
        run: dotnet build src --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test src --configuration Release --no-restore --verbosity normal
